[2024-06-10T07:33:44.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T07:33:44.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-10T07:33:19.984986+00:00 [queued]>
[2024-06-10T07:33:44.652+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-10T07:33:19.984986+00:00 [queued]>
[2024-06-10T07:33:44.663+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-10T07:33:44.701+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): insert_new_row> on 2024-06-10 07:33:19.984986+00:00
[2024-06-10T07:33:44.717+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=19236) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-10T07:33:44.729+0000] {standard_task_runner.py:63} INFO - Started process 19238 to run task
[2024-06-10T07:33:44.727+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'insert_new_row', 'manual__2024-06-10T07:33:19.984986+00:00', '--job-id', '628', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpkzaei52b']
[2024-06-10T07:33:44.734+0000] {standard_task_runner.py:91} INFO - Job 628: Subtask insert_new_row
[2024-06-10T07:33:44.863+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.insert_new_row manual__2024-06-10T07:33:19.984986+00:00 [running]> on host db8c7b709f57
[2024-06-10T07:33:45.158+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='insert_new_row' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T07:33:19.984986+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T07:33:19.984986+00:00'
[2024-06-10T07:33:45.163+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T07:33:45.164+0000] {sql.py:276} INFO - Executing: INSERT INTO table_name_1 VALUES(%s, %s, %s);
[2024-06-10T07:33:45.183+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-10T07:33:45.200+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-10T07:33:45.208+0000] {sql.py:470} INFO - Running statement: INSERT INTO table_name_1 VALUES(%s, %s, %s);, parameters: (555, 'default', datetime.datetime(2024, 6, 10, 7, 33, 38, 153700))
[2024-06-10T07:33:45.214+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-10T07:33:45.216+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T07:33:45.243+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=insert_new_row, run_id=manual__2024-06-10T07:33:19.984986+00:00, execution_date=20240610T073319, start_date=20240610T073344, end_date=20240610T073345
[2024-06-10T07:33:45.291+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T07:33:45.363+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-10T07:33:45.366+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
