[2024-06-19T09:43:19.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T09:43:19.198+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-19T09:43:10.483894+00:00 [queued]>
[2024-06-19T09:43:19.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-19T09:43:10.483894+00:00 [queued]>
[2024-06-19T09:43:19.208+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T09:43:19.223+0000] {taskinstance.py:2330} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_if_table_exists> on 2024-06-19 09:43:10.483894+00:00
[2024-06-19T09:43:19.242+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T09:43:19.245+0000] {standard_task_runner.py:63} INFO - Started process 94 to run task
[2024-06-19T09:43:19.241+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'check_if_table_exists', 'manual__2024-06-19T09:43:10.483894+00:00', '--job-id', '941', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpafz1ewqf']
[2024-06-19T09:43:19.252+0000] {standard_task_runner.py:91} INFO - Job 941: Subtask check_if_table_exists
[2024-06-19T09:43:19.352+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-19T09:43:10.483894+00:00 [running]> on host 3c9100f9b2f4
[2024-06-19T09:43:19.513+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T09:43:10.483894+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T09:43:10.483894+00:00'
[2024-06-19T09:43:19.517+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T09:43:19.565+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-19T09:43:19.571+0000] {sql.py:470} INFO - Running statement: SELECT * FROM information_schema.tables WHERE table_schema = 'public'AND table_name = 'table_name_1';, parameters: None
[2024-06-19T09:43:19.578+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-19T09:43:19.579+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-06-19T09:43:19.581+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-06-19T09:43:19.581+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-06-19T09:43:19.624+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-06-19T09:43:19.690+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T09:43:19.718+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=check_if_table_exists, run_id=manual__2024-06-19T09:43:10.483894+00:00, execution_date=20240619T094310, start_date=20240619T094319, end_date=20240619T094319
[2024-06-19T09:43:19.762+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T09:43:19.802+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-19T09:43:19.804+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
