[2024-06-05T10:26:07.959+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T10:26:07.984+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T10:26:05.345349+00:00 [queued]>
[2024-06-05T10:26:07.995+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T10:26:05.345349+00:00 [queued]>
[2024-06-05T10:26:07.995+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-05T10:26:08.012+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): file_sensor> on 2024-06-05 10:26:05.345349+00:00
[2024-06-05T10:26:08.019+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2207) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T10:26:08.021+0000] {standard_task_runner.py:63} INFO - Started process 2209 to run task
[2024-06-05T10:26:08.022+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'file_sensor', 'manual__2024-06-05T10:26:05.345349+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpns0_d3ai']
[2024-06-05T10:26:08.025+0000] {standard_task_runner.py:91} INFO - Job 338: Subtask file_sensor
[2024-06-05T10:26:08.080+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T10:26:05.345349+00:00 [running]> on host db8c7b709f57
[2024-06-05T10:26:08.212+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T10:26:05.345349+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T10:26:05.345349+00:00'
[2024-06-05T10:26:08.216+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T10:26:08.217+0000] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-06-05T10:26:08.231+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-06-05T10:26:08.232+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-05T10:26:08.236+0000] {filesystem.py:89} INFO - Found File /opt/***/TRIGGER_FILE/file.txt last modified: 20240411090055
[2024-06-05T10:26:08.238+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-05T10:26:08.238+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-05T10:26:08.239+0000] {filesystem.py:89} INFO - Found File /opt/***/TRIGGER_FILE/file.txt last modified: 20240411090055
[2024-06-05T10:26:08.240+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T10:26:08.254+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=trigger_dag_id, task_id=file_sensor, run_id=manual__2024-06-05T10:26:05.345349+00:00, execution_date=20240605T102605, start_date=20240605T102607, end_date=20240605T102608
[2024-06-05T10:26:08.286+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T10:26:08.340+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T10:26:08.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
