[2024-06-19T08:26:56.080+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T08:26:56.134+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-19T08:26:41.361520+00:00 [queued]>
[2024-06-19T08:26:56.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-19T08:26:41.361520+00:00 [queued]>
[2024-06-19T08:26:56.155+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T08:26:56.181+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): insert_new_row> on 2024-06-19 08:26:41.361520+00:00
[2024-06-19T08:26:56.193+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=122) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T08:26:56.197+0000] {standard_task_runner.py:63} INFO - Started process 131 to run task
[2024-06-19T08:26:56.198+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'insert_new_row', 'manual__2024-06-19T08:26:41.361520+00:00', '--job-id', '901', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmptf7v61td']
[2024-06-19T08:26:56.216+0000] {standard_task_runner.py:91} INFO - Job 901: Subtask insert_new_row
[2024-06-19T08:26:56.746+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.insert_new_row manual__2024-06-19T08:26:41.361520+00:00 [running]> on host c44a1a294288
[2024-06-19T08:26:57.208+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='insert_new_row' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T08:26:41.361520+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T08:26:41.361520+00:00'
[2024-06-19T08:26:57.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T08:26:57.278+0000] {sql.py:276} INFO - Executing: INSERT INTO table_name_1 VALUES(%s, %s, %s);
[2024-06-19T08:26:57.343+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-19T08:26:57.367+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-19T08:26:57.398+0000] {sql.py:470} INFO - Running statement: INSERT INTO table_name_1 VALUES(%s, %s, %s);, parameters: (640, 'default', datetime.datetime(2024, 6, 19, 8, 26, 53, 728565))
[2024-06-19T08:26:57.403+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-19T08:26:57.406+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T08:26:57.423+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=insert_new_row, run_id=manual__2024-06-19T08:26:41.361520+00:00, execution_date=20240619T082641, start_date=20240619T082656, end_date=20240619T082657
[2024-06-19T08:26:57.497+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T08:26:57.557+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-19T08:26:57.560+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
