[2024-06-05T11:22:07.425+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T11:22:07.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T11:21:57.944198+00:00 [queued]>
[2024-06-05T11:22:07.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T11:21:57.944198+00:00 [queued]>
[2024-06-05T11:22:07.464+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-05T11:22:07.480+0000] {taskinstance.py:2330} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_if_table_exists> on 2024-06-05 11:21:57.944198+00:00
[2024-06-05T11:22:07.488+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3072) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T11:22:07.491+0000] {standard_task_runner.py:63} INFO - Started process 3074 to run task
[2024-06-05T11:22:07.491+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'check_if_table_exists', 'manual__2024-06-05T11:21:57.944198+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpitxnfn81']
[2024-06-05T11:22:07.495+0000] {standard_task_runner.py:91} INFO - Job 392: Subtask check_if_table_exists
[2024-06-05T11:22:07.553+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T11:21:57.944198+00:00 [running]> on host db8c7b709f57
[2024-06-05T11:22:07.693+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T11:21:57.944198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T11:21:57.944198+00:00'
[2024-06-05T11:22:07.697+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T11:22:07.698+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-06-05T11:22:07.699+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-06-05T11:22:07.700+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-06-05T11:22:07.724+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-06-05T11:22:07.763+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T11:22:07.788+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=check_if_table_exists, run_id=manual__2024-06-05T11:21:57.944198+00:00, execution_date=20240605T112157, start_date=20240605T112207, end_date=20240605T112207
[2024-06-05T11:22:07.836+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T11:22:07.882+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T11:22:07.885+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
