[2024-06-13T12:55:33.636+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T12:55:33.666+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-13T12:55:20.668155+00:00 [queued]>
[2024-06-13T12:55:33.677+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-13T12:55:20.668155+00:00 [queued]>
[2024-06-13T12:55:33.678+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T12:55:33.695+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): insert_new_row> on 2024-06-13 12:55:20.668155+00:00
[2024-06-13T12:55:33.701+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=156) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T12:55:33.703+0000] {standard_task_runner.py:63} INFO - Started process 158 to run task
[2024-06-13T12:55:33.703+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'insert_new_row', 'manual__2024-06-13T12:55:20.668155+00:00', '--job-id', '886', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmp7g_4si_2']
[2024-06-13T12:55:33.706+0000] {standard_task_runner.py:91} INFO - Job 886: Subtask insert_new_row
[2024-06-13T12:55:34.025+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.insert_new_row manual__2024-06-13T12:55:20.668155+00:00 [running]> on host 55555dc522f3
[2024-06-13T12:55:34.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='insert_new_row' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T12:55:20.668155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T12:55:20.668155+00:00'
[2024-06-13T12:55:34.158+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T12:55:34.159+0000] {sql.py:276} INFO - Executing: INSERT INTO table_name_1 VALUES(%s, %s, %s);
[2024-06-13T12:55:34.183+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-13T12:55:34.200+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-13T12:55:34.207+0000] {sql.py:470} INFO - Running statement: INSERT INTO table_name_1 VALUES(%s, %s, %s);, parameters: (796, 'default', datetime.datetime(2024, 6, 13, 12, 55, 32, 25733))
[2024-06-13T12:55:34.210+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-13T12:55:34.212+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T12:55:34.227+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=insert_new_row, run_id=manual__2024-06-13T12:55:20.668155+00:00, execution_date=20240613T125520, start_date=20240613T125533, end_date=20240613T125534
[2024-06-13T12:55:34.254+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T12:55:34.284+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T12:55:34.287+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
