[2024-06-10T07:48:55.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T07:48:55.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.query_the_table manual__2024-06-10T07:48:41.580101+00:00 [queued]>
[2024-06-10T07:48:55.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.query_the_table manual__2024-06-10T07:48:41.580101+00:00 [queued]>
[2024-06-10T07:48:55.350+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-10T07:48:55.365+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgreSQLCountRows): query_the_table> on 2024-06-10 07:48:41.580101+00:00
[2024-06-10T07:48:55.372+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=19522) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-10T07:48:55.374+0000] {standard_task_runner.py:63} INFO - Started process 19524 to run task
[2024-06-10T07:48:55.374+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'query_the_table', 'manual__2024-06-10T07:48:41.580101+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpjagdt23g']
[2024-06-10T07:48:55.377+0000] {standard_task_runner.py:91} INFO - Job 659: Subtask query_the_table
[2024-06-10T07:48:55.431+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.query_the_table manual__2024-06-10T07:48:41.580101+00:00 [running]> on host db8c7b709f57
[2024-06-10T07:48:55.565+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='query_the_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T07:48:41.580101+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T07:48:41.580101+00:00'
[2024-06-10T07:48:55.570+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T07:48:55.588+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-10T07:48:55.597+0000] {sql.py:470} INFO - Running statement: SELECT COUNT(*) FROM table_name_1;, parameters: None
[2024-06-10T07:48:55.599+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-10T07:48:55.625+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T07:48:55.639+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=query_the_table, run_id=manual__2024-06-10T07:48:41.580101+00:00, execution_date=20240610T074841, start_date=20240610T074855, end_date=20240610T074855
[2024-06-10T07:48:55.679+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T07:48:55.706+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-10T07:48:55.708+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
