[2024-06-11T13:13:43.834+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T13:13:43.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.query_the_table manual__2024-06-11T13:13:23.455869+00:00 [queued]>
[2024-06-11T13:13:43.882+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.query_the_table manual__2024-06-11T13:13:23.455869+00:00 [queued]>
[2024-06-11T13:13:43.883+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T13:13:43.900+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgreSQLCountRows): query_the_table> on 2024-06-11 13:13:23.455869+00:00
[2024-06-11T13:13:43.910+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T13:13:43.913+0000] {standard_task_runner.py:63} INFO - Started process 105 to run task
[2024-06-11T13:13:43.913+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'query_the_table', 'manual__2024-06-11T13:13:23.455869+00:00', '--job-id', '806', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpvkkxohxz']
[2024-06-11T13:13:43.916+0000] {standard_task_runner.py:91} INFO - Job 806: Subtask query_the_table
[2024-06-11T13:13:43.976+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.query_the_table manual__2024-06-11T13:13:23.455869+00:00 [running]> on host eeaea8b2797f
[2024-06-11T13:13:44.300+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='query_the_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T13:13:23.455869+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T13:13:23.455869+00:00'
[2024-06-11T13:13:44.304+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T13:13:44.348+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-11T13:13:44.355+0000] {sql.py:470} INFO - Running statement: SELECT COUNT(*) FROM table_name_1;, parameters: None
[2024-06-11T13:13:44.357+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-11T13:13:44.382+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T13:13:44.398+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=query_the_table, run_id=manual__2024-06-11T13:13:23.455869+00:00, execution_date=20240611T131323, start_date=20240611T131343, end_date=20240611T131344
[2024-06-11T13:13:44.435+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-11T13:13:44.467+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-11T13:13:44.469+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
