[2024-06-10T07:48:49.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T07:48:49.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-10T07:48:41.580101+00:00 [queued]>
[2024-06-10T07:48:50.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-10T07:48:41.580101+00:00 [queued]>
[2024-06-10T07:48:50.009+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-10T07:48:50.026+0000] {taskinstance.py:2330} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_if_table_exists> on 2024-06-10 07:48:41.580101+00:00
[2024-06-10T07:48:50.033+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=19516) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-10T07:48:50.035+0000] {standard_task_runner.py:63} INFO - Started process 19518 to run task
[2024-06-10T07:48:50.035+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'check_if_table_exists', 'manual__2024-06-10T07:48:41.580101+00:00', '--job-id', '657', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpj_vzjr9c']
[2024-06-10T07:48:50.038+0000] {standard_task_runner.py:91} INFO - Job 657: Subtask check_if_table_exists
[2024-06-10T07:48:50.088+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-10T07:48:41.580101+00:00 [running]> on host db8c7b709f57
[2024-06-10T07:48:50.196+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T07:48:41.580101+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T07:48:41.580101+00:00'
[2024-06-10T07:48:50.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T07:48:50.209+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-10T07:48:50.214+0000] {sql.py:470} INFO - Running statement: SELECT * FROM information_schema.tables WHERE table_schema = 'public'AND table_name = 'table_name_1';, parameters: None
[2024-06-10T07:48:50.217+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-10T07:48:50.218+0000] {logging_mixin.py:188} INFO - ('***', 'public', 'table_name_1', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
[2024-06-10T07:48:50.219+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-06-10T07:48:50.219+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-06-10T07:48:50.220+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-06-10T07:48:50.237+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-06-10T07:48:50.263+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T07:48:50.285+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=check_if_table_exists, run_id=manual__2024-06-10T07:48:41.580101+00:00, execution_date=20240610T074841, start_date=20240610T074850, end_date=20240610T074850
[2024-06-10T07:48:50.340+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T07:48:50.380+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-10T07:48:50.382+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
