[2024-06-05T12:01:34.842+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T12:01:34.880+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T12:01:22.965377+00:00 [queued]>
[2024-06-05T12:01:34.891+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T12:01:22.965377+00:00 [queued]>
[2024-06-05T12:01:34.897+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-05T12:01:34.969+0000] {taskinstance.py:2330} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_if_table_exists> on 2024-06-05 12:01:22.965377+00:00
[2024-06-05T12:01:34.975+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3829) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T12:01:34.977+0000] {standard_task_runner.py:63} INFO - Started process 3832 to run task
[2024-06-05T12:01:34.978+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'check_if_table_exists', 'manual__2024-06-05T12:01:22.965377+00:00', '--job-id', '477', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpjmos5qq6']
[2024-06-05T12:01:34.981+0000] {standard_task_runner.py:91} INFO - Job 477: Subtask check_if_table_exists
[2024-06-05T12:01:35.058+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T12:01:22.965377+00:00 [running]> on host db8c7b709f57
[2024-06-05T12:01:35.237+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T12:01:22.965377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T12:01:22.965377+00:00'
[2024-06-05T12:01:35.241+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T12:01:35.242+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-06-05T12:01:35.243+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-06-05T12:01:35.244+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-06-05T12:01:35.272+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-06-05T12:01:35.310+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T12:01:35.339+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=check_if_table_exists, run_id=manual__2024-06-05T12:01:22.965377+00:00, execution_date=20240605T120122, start_date=20240605T120134, end_date=20240605T120135
[2024-06-05T12:01:35.405+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T12:01:35.452+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T12:01:35.454+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
