[2024-06-04T15:09:26.326+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T15:09:26.353+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-04T15:09:17.085651+00:00 [queued]>
[2024-06-04T15:09:26.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-04T15:09:17.085651+00:00 [queued]>
[2024-06-04T15:09:26.363+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-04T15:09:26.378+0000] {taskinstance.py:2330} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_if_table_exists> on 2024-06-04 15:09:17.085651+00:00
[2024-06-04T15:09:26.385+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=262) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T15:09:26.387+0000] {standard_task_runner.py:63} INFO - Started process 264 to run task
[2024-06-04T15:09:26.387+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'check_if_table_exists', 'manual__2024-06-04T15:09:17.085651+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmph9yjso4f']
[2024-06-04T15:09:26.390+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask check_if_table_exists
[2024-06-04T15:09:26.445+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-04T15:09:17.085651+00:00 [running]> on host cd2a5574829a
[2024-06-04T15:09:26.550+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T15:09:17.085651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T15:09:17.085651+00:00'
[2024-06-04T15:09:26.553+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T15:09:26.554+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-06-04T15:09:26.555+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-06-04T15:09:26.555+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-06-04T15:09:26.572+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-06-04T15:09:26.596+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T15:09:26.616+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=check_if_table_exists, run_id=manual__2024-06-04T15:09:17.085651+00:00, execution_date=20240604T150917, start_date=20240604T150926, end_date=20240604T150926
[2024-06-04T15:09:26.653+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-04T15:09:26.688+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T15:09:26.690+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
