[2024-06-07T10:29:02.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T10:29:02.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-07T10:28:53.809662+00:00 [queued]>
[2024-06-07T10:29:02.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.insert_new_row manual__2024-06-07T10:28:53.809662+00:00 [queued]>
[2024-06-07T10:29:02.646+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-07T10:29:02.664+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): insert_new_row> on 2024-06-07 10:28:53.809662+00:00
[2024-06-07T10:29:02.673+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=13507) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T10:29:02.675+0000] {standard_task_runner.py:63} INFO - Started process 13509 to run task
[2024-06-07T10:29:02.675+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'insert_new_row', 'manual__2024-06-07T10:28:53.809662+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpou3wj9qr']
[2024-06-07T10:29:02.678+0000] {standard_task_runner.py:91} INFO - Job 597: Subtask insert_new_row
[2024-06-07T10:29:02.733+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.insert_new_row manual__2024-06-07T10:28:53.809662+00:00 [running]> on host db8c7b709f57
[2024-06-07T10:29:02.896+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='insert_new_row' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T10:28:53.809662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-07T10:28:53.809662+00:00'
[2024-06-07T10:29:02.899+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T10:29:02.900+0000] {sql.py:276} INFO - Executing: INSERT INTO table_name_1 VALUES(%s, %s, %s);
[2024-06-07T10:29:02.912+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-07T10:29:02.921+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-07T10:29:02.926+0000] {sql.py:470} INFO - Running statement: INSERT INTO table_name_1 VALUES(%s, %s, %s);, parameters: (467, 'default', datetime.datetime(2024, 6, 7, 10, 29, 1, 411259))
[2024-06-07T10:29:02.928+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-07T10:29:02.929+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T10:29:02.940+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=insert_new_row, run_id=manual__2024-06-07T10:28:53.809662+00:00, execution_date=20240607T102853, start_date=20240607T102902, end_date=20240607T102902
[2024-06-07T10:29:02.981+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-07T10:29:03.007+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-07T10:29:03.009+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
